[package]
name = "cavey"
version = "0.1.0"
authors = ["J. Cliff Dyer <jcd@sdf.org>"]
edition = "2018"

[dependencies]
structopt = "0.2"
failure = "0.1"
serde = "1.0"
serde_json = "1.0"

[dev-dependencies]
assert_cmd = "0.11"
predicates = "1.0"
walkdir = "2.2"
tempfile = "3.0"
